### ISSUE TITLE
Does not support data-driven tests

### ISSUE THREAD

**Issue by srigor** [saucelabs/sauce-java#11]
I have found that running a TestNG data-driven test using SauceOnDemandTestListener.class does not work correctly.  For a data-driven test, one @Test is run several times for the number of rows in a CSV as an example. Using SauceOnDemandTestListener, the Sauce Labs job is marked as pass if a row of test data passes, and marked as failed if a row of test data fails. So the entire job passes if the LAST row of test data passes, and fails if the LAST row of test data fails.

I actually ended up adding to the SauceOnDemandTestListener. I added a boolean called passed to the class and set it to true by default. 
```
private boolean passed = true;
```

I then modified onTestFailure method by adding the following if logic:
```
if (this.passed) { this.passed = false; }
```

And finally modified onTestSuccess with:
```
if (this.passed) { markJobAsPassed(); }
```

That way, if a failure happens, the job will never be marked as passed in subsequent tests for a data-driven test. May not be the best way to handle the issue, but it's worked for me so far.

**Comment by mehmetg** [comment]
closing as per previous comment.
