### ISSUE TITLE
Make v2.1.11 available on the Central Repository

### ISSUE THREAD

**Issue by andham** [saucelabs/sauce-java#21]
v2.1.11 doesn't exist on the Central Repository. Please make it available!

**Comment by rossrowe** [comment]
Apologies for the inconvenience, I've updated the pom to support both the Maven Central and Sauce Labs repositories, and have deployed this as version 2.1.13 to Maven Central

**Comment by andham** [comment]
Thanks. Don't forget to update docs (like tutorial) where v2.1.11 is mentioned.
