### ISSUE TITLE
Running a test is throwing initialization error

### ISSUE THREAD

**Issue by sivakumar15** [saucelabs/sauce-java#22]
Tried running a test SampleSauceTest with ConcurrentParameterized.class on Sauce lab is throwing initialization error. Could you please help me on fixing this issue

**Comment by rossrowe** [comment]
Hi, can you please attach the stack trace for the error message?  I just ran the test in my environment and it seemed to work okay

**Comment by sivakumar15** [comment]
Actually I tried to run SampleSauceTest tests in parallel using @RunWith(ConcurrentParameterized.class) but for some reason but for some reason its failed with initialization error. When looked at other options found that Sauce lab has another class called Parallelized and with this able to run tests in parallel across different platforms/browsers. Could you please tell me the difference between ConcurrentParameterized.class and Parallelized class. With the Parallelized one observed that tests are running across specified platforms parallely on Sauce labs.


Thanks in advance for your help
Sivakumar

**Comment by sivakumar15** [comment]
Is it possible to run a test on selenium grid in bamboo sequentially only once but  running the same test on sauce lab parallely using any specific condition? If I use the annotation @Paralleilized to run test parallely on Sauce lab then tests are failing on Selenium grid in Bamboo with illegal argument exception. Is there any way to fix this issue?


Thanks in advance for your help
Sivakumar


From: <Nallusamy>, Sivakumar Nallusamy <sivakn@cobalt.com<mailto:sivakn@cobalt.com>>
Date: Wednesday, April 22, 2015 at 6:55 PM
To: saucelabs/sauce-java <reply@reply.github.com<mailto:reply@reply.github.com>>
Cc: Sivakumar Nallusamy <sivakn@cobalt.com<mailto:sivakn@cobalt.com>>
Subject: Re: [sauce-java] Running a test is throwing initialization error (#22)

Actually I tried to run SampleSauceTest tests in parallel using @RunWith(ConcurrentParameterized.class) but for some reason but for some reason its failed with initialization error. When looked at other options found that Sauce lab has another class called Parallelized and with this able to run tests in parallel across different platforms/browsers. Could you please tell me the difference between ConcurrentParameterized.class and Parallelized class. With the Parallelized one observed that tests are running across specified platforms parallely on Sauce labs.


Thanks in advance for your help
Sivakumar

**Comment by rossrowe** [comment]
I haven't been able to replicate the initialization error using the ConcurrentParameterized class, can you attach the stack trace of the error, and also let me know what version of the sauce_junit library you're using?

With regards to running tests in sequence/parallel based on arbitrary conditions, I don't think this is possible using the @RunWith annotations, but it's probably possible if you develop some custom code to perform this.

**Comment by mehmetg** [comment]
Please reopen, if this is still an issue.
