### ISSUE TITLE
I need sauce connect 4.3.9

### ISSUE THREAD

**Issue by RubenRose** [saucelabs/sauce-java#23]
@rossrowe 

I am using sauce-connect-plugin in my project

                                               <groupId>com.saucelabs.maven.plugin</groupId>
						<artifactId>sauce-connect-plugin</artifactId>
						<version>2.1.13</version>

But, I have had problems with sauce connect, as the session connects and disconnects several times. I contacted the support of SauceLabs and he asked me to change the sauce connect 4.3 to 4.3.9.
Could You  update the plugin?

Thanks in advance,

Ruben Rose

========== saucelabs email ============================
Good Afternoon Ruben,
I noticed we are using Sauce Connect 4.3. Sauce Connect has gone through a lot of versions since then and I’d like to make sure this isn’t a problem we have solved in those iterations.
Could you please grab the latest version 4.3.9 from https://docs.saucelabs.com/reference/sauce-connect/ and try this again?
Colin

**Comment by rossrowe** [comment]
Hi, thanks for letting me know, I've released version 2.1.20 of the Sauce
Connect maven plugin which should include Sauce Connect 4.3.9, can you try
this version and let me know how it goes?

**Comment by RubenRose** [comment]
Ross,
it's ok now.
Thanks.
