### ISSUE TITLE
TestNG listener @Listeners({SauceOnDemandTestListener.class}) only works when the tests are methods oriented

### ISSUE THREAD

**Issue by theCampbell** [saucelabs/sauce-java#24]
The following was reported to Sauce Labs support, reiterating here for consideration.
*************************************************************************************
the TestNG listener @Listeners({SauceOnDemandTestListener.class}) only
works when the tests are methods oriented. When the tests are classes
oriented it doesn’t work, because the result of the last method that
matters. Example: If You have 1 class with 5 methods and the first 4 FAIL
and the last one PASS, so the final result is PASS for whole the class test.

Workaround: I am not using @Listener. I am using sauceRest. You can keep
two @Listener version, one for methods and another for classes oriented.

@AfterClass(alwaysRun = *true*)

*public* *void* tearDown() {

SauceREST sauceREST = *new* SauceREST(USUARIO_SAUCELAB,
ACCESSKEY_SAUCELAB);

*if*(isTestSuccesful) {

sauceREST.jobPassed(getSessionId());

} *else* {

sauceREST.jobFailed(getSessionId());

}

driver.quit();

}

@AfterMethod

*public* *void* avaliaResultadoTeste(ITestResult result) {

*if*(!result.isSuccess()) {

isTestSuccesful = Boolean.*FALSE*;

}

}

**Comment by mehmetg** [comment]
No longer valid. Cannot reproduce.
