### ISSUE TITLE
SauceOnDemandTestListener causes tests to crash locally

### ISSUE THREAD

**Issue by saucyallison** [saucelabs/sauce-java#25]
Sauce Labs Support received this report:
_______________________
HI, We have both tests that we want to run on our local systems and tests that we want to run with cross browser functionality.  As such, we implement our own custom listener which we want to use when on our system, and the SauceLabOnDemandListener when using sauce lab.  However, even when we set SELENIUM_IS_LOCAL to True, SauceLabOnDemandListener still is somehow active and causes tests to crash when running on our local machines.  We looked into the SauceLab listener and found that in many methods, computation takes place BEFORE the check to see if SELENIUM_IS_LOCAL, which we believe may be the cause for these failures.These methods 'onTestStart(ITestResult result)", "onTestFailure(ITestResult tr)", "onTestSuccess(ITestResult tr)" are performed functionalities before it returns.  This cause our CustomListener to crash.  Shouldn't it return immediately if isLocal is true without performing any function?
_______________________
Thank you!

**Comment by mehmetg** [comment]
This should be resolved now.

**Comment by javydreamercsw** [comment]
What's the resolution?
