### ISSUE TITLE
Using snapshot of 2.1.21 in TestNG example

### ISSUE THREAD

**Issue by s3ck** [saucelabs/sauce-java#26]
The pom.xml in the TestNG example is pointing to a SNAPSHOT. Using 2.1.20 will find the correct dependency and compile.

**Comment by Jonahss** [comment]
Interested in submitting a Pull Request to correct it?
If not, we can take care of it.

**Comment by s3ck** [comment]
Ok it is in #27.

**Comment by mehmetg** [comment]
Closing as per comments on  #27
