### ISSUE TITLE
TestWatcher proxy support

### ISSUE THREAD

**Issue by dankirberger** [saucelabs/sauce-java#28]
When executing tests from our desktop on SauceLabs, we must pass through a corporate firewall (which currently involves a very awkward Selenium custom HttpExecutor configuration).

Could support be added to the SauceOnDemandTestWatcher to support proxies as well? I think we would just need to pass in a Proxy object to SauceREST and use that in the url.openConnection() call.

**Comment by mehmetg** [comment]
@dankirberger Have you taken a look at this? https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html Feel free to reopen, it the linked info does not help.
