### ISSUE TITLE
sauce-connect-plugin proxy support

### ISSUE THREAD

**Issue by hennr** [saucelabs/sauce-java#38]
Hi guys,
 not sure if I just don't see it or if it's really not there.

I miss an option to set a proxy in the sauce-connect-plugin config.
I only have the option to run my project with -p http://my.proxy:8080 but this is not an option in some cases for me. What I would really appreciate would be something like:

```
<plugin>
    <groupId>com.saucelabs.maven.plugin</groupId>
    <artifactId>sauce-connect-plugin</artifactId>
    <version>2.1.13</version>
        <configuration>
            <sauceUsername>user</sauceUsername>
            <sauceAccessKey>accesskey</sauceAccessKey>
            <http_proxy>http://my.proxy:8080</http_proxy>
            <https_proxy>http://my.proxy:8080</https_proxy>
        </configuration>
...
</plugin>
```

What do you say?

**Comment by mehmetg** [comment]
@hennr Did you try to use the `<options>-p my.proxy.com:80</options>`config line.

**Comment by hennr** [comment]
@mehmetg Not yet, thanks for the hint. I will try it soon.

**Comment by hennr** [comment]
@mehmetg I tried it but our setup is broken in general, so I'm not sure that it works. It makes sense though and so I'm closing this issue now.
Thanks for your input!
