### ISSUE TITLE
sauce-connect-plugin not allow two options configurations

### ISSUE THREAD

**Issue by pagu23** [saucelabs/sauce-java#42]
It is not possible to add two options configurations

not working:
`<configuration>
...
<options>-p testproxy:3128</options>
<options>-i local_test</options>
...
</configuration>`

working:
`<configuration>
...
<options>-p testproxy:3128</options>
...
</configuration>`

or

`<configuration>
...
<options>-i local_test</options>
...
</configuration>`

Is it possible to fix this bug or is this an expected behaviour?

**Comment by mikeastarb** [comment]
I believe you can do something like

<configuration> ... <options>-p testproxy:3128 -i local_test</options> ... </configuration>

At least, that's what I'm doing to run with multiple custom options
