### ISSUE TITLE
Failing to Start Sauce Connect on start-sauceconnect

### ISSUE THREAD

**Issue by mikeastarb** [saucelabs/sauce-java#45]
I'm having an issue with the Sauce Connect Plugin when trying to start up a tunnel for my tests.

start-sauceconnect is able to reach out to SauceLabs and create a tunnel for me, but once it gets to a phase where it's started the SeleniumListener on port 4445, it's immediately shutting the tunnel back down, then starting my tests. When starting sc from the command line however, I am able to fully connect with the same command line settings when I do it manually.

Attached is the output log from SauceConnect
[sc_localComputer.txt](https://github.com/saucelabs/sauce-java/files/593121/sc_localComputer.txt)

Any ideas?

**Comment by mikeastarb** [comment]
Fixed it. Needed the -T parameter along with my -p parameter

**Comment by eddiewebb** [comment]
Can someone mark this as resolved?

**Comment by mikeastarb** [comment]
Resolved
