### ISSUE TITLE
Unit tests and code coverage not executing for new test class

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/sauce-java#72]
I added a new class called SauceHelperTests in com.saucelabs.common. This class has some unit tests. The unit tests are not executing and code coverage isn't picking them up. Looks like we need to make some update to the CI build configuration.

**Comment by nadvolod** [comment]
@joshgrantsauce do you know how to resolve that issue? What do I have to do?

**Comment by joshgrantsauce** [comment]
@nadvolod looks like the root pom.xml doesn't find the subproject tests. There's probably a few ways to fix this. I'd try updating the root pom.xml to look through the all subprojects but I'll see what the best approach is here.

**Comment by nikolay-advolodkin** [comment]
Issue resolved. It had to do with the naming convention of the files.
https://stackoverflow.com/questions/6178583/maven-does-not-find-junit-tests-to-run
